<br><br><br><br><br>
<div class="container ">

<?php
if (isset($_SESSION['msg'])) {
?>
            <div class="col-md-8 my-4 mx-auto">
                <div class="alert alert-<?= $_SESSION['color'] ?> alert-dismissible fade show" role="alert">
                    <?= $_SESSION['msg'] ?>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        <?php
            unset($_SESSION['msg'], $_SESSION['color']);
        }


        ?>
    <div class="row">
        <div class="card card-body col-md-6 mx-auto">
            <div class="h5">Crear producto</div>
            <form method="post" action="<?= BASE_URL . 'producto/store' ?>" class="my-4">
                <div class="form-group">
                    <label>Producto</label>
                    <input type="text" name="nom"  class="form-control">
                </div>

                <div class=" row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Stok</label>
                            <input type="text" name="stok"  class="form-control">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Valor</label>
                            <input type="text" name="val"  class="form-control">
                        </div>
                    </div>
                </div>
                <label>Estado</label>
                <select name="estado" class="form-control">
                    <option value="disponible">Disponible</option>
                    <option value="agotado">Agotado</option>
                    <select>

                        <label>Estado</label>
                        <select name="categoria" class="form-control">
                            <?php
                            foreach ($this->categorias as $i => $c) echo '<option ' . (isset($_POST['categoria']) && $_POST['categoria'] == $i ? ' selected ' : '') . ' value="' . $i . '">' . $c . '</option>'
                            ?>
                            <select>

                                <div class="form-group my-2">
                                    <label>Descripción</label>
                                    <textarea name="descript" class="form-control"></textarea>
                                </div>

                                <div class="form-group my-4">
                                    <input type="submit" value="Guardar" class="form-control btn btn-primary">
                                </div>
            </form>
        </div>



    </div>
    


</div>