<br><br><br><br><br>
<?php

if ($this->data['status'] == 'ok') {
    $u = $this->data['msg'];
?>
    <div class="container ">
        <div class="row">

            <div class="card card-body col-md-6 mx-auto">
                <div class="h5">Editar producto</div>
                <form method="post" action="<?= BASE_URL . 'producto/update' ?>" class="my-4">
                    <div class="form-group">
                        <label>Producto</label>
                        <input type="text" name="nom" value="<?= $u[0] ?>" class="form-control">
                    </div>

                    <div class=" row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Stok</label>
                                <input type="text" name="stok" value="<?= $u[2] ?>" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Valor</label>
                                <input type="text" name="val" value="<?= $u[1] ?>" class="form-control">
                            </div>
                        </div>
                    </div>
                    <label>Categoria</label>
                    <select name="categoria" class="form-control">
                        <?php
                        foreach ($this->categorias as $i => $d) echo '<option ' . ($i == $u[11] ? ' selected ' : '') . ' value="' . $i . '">' . $d . '</option>'
                        ?>
                        <select>

                            <label>Estado</label>
                            <select name="estado" class="form-control">
                                <?php
                                foreach (['agotado' => 'Agotado', 'disponible' => 'Disponible'] as $i => $d) echo '<option ' . ($i == $u[10] ? ' selected ' : '') . ' value="' . $i . '">' . $d . '</option>'
                                ?>
                                <select>
                                    <div class="form-group my-2">
                                        <label>Descripción</label>
                                        <textarea name="descript" class="form-control"><?= $u[4] ?></textarea>
                                    </div>

                                    <div class="form-group my-4">
                                    <input type="hidden" name="id_prod" value="<?= $u[9] ?>">
                                    <input type="hidden" name="updated_at" value="<?= $u[6] ?>">
                                        <input type="submit" value="Guardar" class="form-control btn btn-primary">
                                    </div>
                </form>
            </div>
        </div>
    </div>
<?php
} else {
?>
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <?= $this->data['msg'] ?>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    </div>
<?php
}
?>