<br><br><br><br><br>

<div class="container ">

    <?php
    if (isset($_SESSION['msg'])) {
    ?>
        <div class="col-md-8 my-4 mx-auto">
            <div class="alert alert-<?= $_SESSION['color'] ?> alert-dismissible fade show" role="alert">
                <?= $_SESSION['msg'] ?>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    <?php
        unset($_SESSION['msg'], $_SESSION['color']);
    }
    ?>
    <div class="row">
        <?php
        if ($this->data['status'] == 'ok') {
        ?>
            <div class="col-md-10 mx-auto">
                <a type="buttom" class="my-2 btn btn-success" href="<?= BASE_URL . 'producto/create' ?>">Nuevo</a>

                <table class="table table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Nombre Producto</th>
                            <th scope="col">Precio</th>
                            <th scope="col">Stok</th>
                            <th scope="col">Estado</th>
                            <th scope="col">Categotia</th>
                            <th scope="col">Creado</th>
                            <th scope="col">Actualizado</th>
                            <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->data['msg'] as $i => $d) {
                        ?>
                            <tr>
                                <th><?= $d[0] ?></th>
                                <td><?= $d[1] ?></td>
                                <td><?= $d[2] ?></td>
                                <td><?= $d[3] ?></td>
                                <td><?= $d[8] ?></td>
                                <td><?= $d[7] ?></td>
                                <td><?= $d[6] ?></td>

                                <td>

                                    <form method="post" style="display :inline">
                                        <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                        <input type="hidden" name="a" value="dlt">
                                        <input type="hidden" name="id" value="<?= $d[9]  ?>">
                                    </form>
                                    <form method="post" style="display :inline">
                                        <button type="submit" class="btn btn-info my-2" href="" class="my-2 btn btn-info"><i class="fas fa-pencil-alt"></i></button>
                                        <input type="hidden" name="id" value="<?= $d[9] ?>">
                                        <input type="hidden" name="a" value="edt">
                                    </form>

                                </td>
                            </tr>
                        <?php
                        }

                        ?>
                </table>
            </div>
        <?php
        }
        ?>
    </div>
</div>